name: build n' deploy MkDocs to GitHub pages
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - mkdocs.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: install mkdocs
        run: pip install mkdocs
      - name: deploy mkdocs
        run: mkdocs gh-deploy --force --clean --verbose